# Generated by Django 5.2.7 on 2025-10-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailystretch_app', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
