# Generated by Django 5.2.7 on 2025-10-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailystretch_app', '0004_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='break_duration',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='study_duration',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
